### ISSUE TITLE
CI build status

### ISSUE THREAD

**Issue by avdgaag** [avdgaag/wally#5]
Accept updates about CI build status. This is currently implemented for Codeship, but maybe this can be adapted to support other services (at the very least, it should not be hard to do so). Also, check if we can support three states: passed, failed and running.

**Comment by florish** [comment]
Just wondering: could it be an option to listen to GitHub's commit status changes? 

GitHub supports tons of Events for use in webhooks, including the [StatusEvent](https://developer.github.com/v3/activity/events/types/#statusevent). This event seems to be fired whenever a commit status is changed.

Of course, this only replaces a CI dependency (Codeship) with a Git provider dependency (GitHub), but as we'll probably need GitHub events for monitoring Pull Request status anyway, it might reduce the overall number of external services needed.

**Comment by avdgaag** [comment]
> could it be an option to listen to GitHub's commit status changes

Yes, this would be preferable as GitHub's commit status might be composed of various different checks. Then again, not all projects use GitHub and maybe you really are interested in just the CodeShip build status and not any other checks that make up GitHub's commit status (such as CodeClimate or Coveralls etc.).

My guess is we need to support both, and then prefer to configure just the GitHub commit status.
